name: macOS

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        config:
        - os: macos-12
          xcode: '14.0.1'
        - os: macos-latest
          xcode: '16.0'
    runs-on: ${{ matrix.config.os }}
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.config.xcode }}.app/Contents/Developer
    steps:
      - uses: actions/checkout@v4
      - name: Run CMake
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Debug
      - name: Build
        run: cmake --build build
      - name: Test skt executable
        run: cd build ; ctest -V ; [ -s sktdoc.tex ] || exit 1
